export { default as TagsInput } from './CNTagsInput.vue'
export { default as TagsInputInput } from './CNTagsInputInput.vue'
export { default as TagsInputItem } from './CNTagsInputItem.vue'
export { default as TagsInputItemDelete } from './CNTagsInputItemDelete.vue'
export { default as TagsInputItemText } from './CNTagsInputItemText.vue'
