export { default as Pagination } from './CNPagination.vue'
export { default as PaginationContent } from './CNPaginationContent.vue'
export { default as PaginationEllipsis } from './CNPaginationEllipsis.vue'
export { default as PaginationFirst } from './CNPaginationFirst.vue'
export { default as PaginationItem } from './CNPaginationItem.vue'
export { default as PaginationLast } from './CNPaginationLast.vue'
export { default as PaginationNext } from './CNPaginationNext.vue'
export { default as PaginationPrevious } from './CNPaginationPrevious.vue'
